"use client";
import {FormEvent,useEffect,useState} from "react";
import {Project,request} from "@/lib/api";
export function ProjectDashboard(){
 const [projects,setProjects]=useState<Project[]>([]),[error,setError]=useState("");
 const load=()=>request<Project[]>("/projects").then(setProjects).catch(e=>setError(e.message));useEffect(load,[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setError("");const f=new FormData(e.currentTarget);try{await request("/projects",{method:"POST",body:JSON.stringify({name:f.get("name"),mode:f.get("mode"),objective:f.get("objective"),created_by:"workspace-user"})});e.currentTarget.reset();load()}catch(e){setError(e instanceof Error?e.message:"Request failed")}}
 return <div className="grid"><section className="card create"><div className="eyebrow">New research</div><h2>Open an evidence trail.</h2><form className="fields" onSubmit={submit}><div className="field"><label>Project name</label><input name="name" required placeholder="Healthy kitchen opportunity"/></div><div className="field"><label>Entry mode</label><select name="mode"><option value="DISCOVERY">Discovery</option><option value="DEEP_RESEARCH">Deep Research</option><option value="CUSTOMER_FIRST">Customer-first</option><option value="KEYWORD_FIRST">Keyword-first</option></select></div><div className="field"><label>Objective or seed</label><textarea name="objective" required placeholder="What do you want to understand?"/></div><button className="button">Create project</button>{error&&<div className="error">{error}</div>}</form></section><section className="card projects"><div className="eyebrow">Research projects</div><h2>Work in progress</h2>{projects.length===0?<div className="empty">No projects yet. Create one to begin with a human-reviewed scope.</div>:projects.map(p=><a className="project" href={`/projects/${p.id}`} key={p.id}><div><strong>{p.name}</strong><div className="meta"><span>{p.objective}</span></div></div><span className="tag">{p.mode.replaceAll("_"," ")}</span></a>)}</section></div>
}
