"use client";
import {useEffect,useState} from "react";
import {Evidence,Project,request,Workflow} from "@/lib/api";
import {canDecide, HumanDecision} from "@/lib/workflow";
export function Workspace({id}:{id:string}){
 const [project,setProject]=useState<Project|null>(null),[workflow,setWorkflow]=useState<Workflow|null>(null),[evidence,setEvidence]=useState<Evidence[]>([]),[error,setError]=useState("");
 const load=()=>Promise.all([request<Project>(`/projects/${id}`),request<Workflow>(`/projects/${id}/workflow`),request<Evidence[]>(`/projects/${id}/evidence`)]).then(([p,w,e])=>{setProject(p);setWorkflow(w);setEvidence(e)}).catch(e=>setError(e.message));useEffect(load,[id]);
 async function action(evidenceId:string,action:string){try{await request(`/projects/${id}/evidence/${evidenceId}/actions`,{method:"POST",body:JSON.stringify({action,actor_id:"workspace-user"})});load()}catch(e){setError(e instanceof Error?e.message:"Action failed")}}
 async function decide(decision:HumanDecision){try{await request(`/projects/${id}/decisions`,{method:"POST",body:JSON.stringify({decision,actor_type:"HUMAN",actor_id:"workspace-user"})});load()}catch(e){setError(e instanceof Error?e.message:"Decision failed")}}
 if(error&&!project)return <main className="shell"><div className="error">{error}</div></main>;if(!project||!workflow)return <main className="shell">Loading workspace…</main>;
 return <main className="shell"><header className="topbar"><a className="brand" href="/">AMI / Research Desk</a><div className="status"><span className="dot"/><strong>{workflow.current_stage}</strong><span className="tag">{workflow.state}</span></div></header><div className="eyebrow" style={{marginTop:28}}>{project.mode.replaceAll("_"," ")}</div><h1 style={{fontSize:48}}>{project.name}</h1><p className="sub">{project.objective}</p>{error&&<div className="error">{error}</div>}<div className="workspace"><section className="card panel"><div className="eyebrow">01 / Evidence</div><h2>Source records</h2>{evidence.length===0?<div className="empty">No evidence has been collected. Missing evidence remains missing; analysis cannot claim facts yet.</div>:evidence.map(e=><article className="evidence" key={e.id}><strong>{e.summary}</strong><div className="meta"><span>Source: {e.source_ref}</span><span>{Math.round(e.confidence*100)}% confidence</span><span>{e.freshness}</span>{e.estimated&&<span>ESTIMATED</span>}</div><div className="actions"><button className="button secondary" onClick={()=>action(e.id,"PIN")}>{e.pinned?"Pinned":"Pin"}</button><button className="button secondary" onClick={()=>action(e.id,"REJECT")}>{e.rejected?"Rejected":"Reject"}</button><button className="button secondary" onClick={()=>action(e.id,"RESTORE")}>Restore</button></div></article>)}</section><section className="card panel"><div className="eyebrow">02 / Analysis</div><h2>Deterministic signals</h2><div className="empty">Analysis appears only after validated source data is available. AI observations will remain separate from facts and cite evidence IDs.</div></section><aside className="card panel"><div className="eyebrow">03 / Decision</div><h2>Human gate</h2><p className="meta">Current state</p><h3>{workflow.state.replaceAll("_"," ")}</h3>{workflow.blocked_reason&&<div className="error">{workflow.blocked_reason}</div>}<div className="actions"><button disabled={!canDecide(workflow.state,"APPROVE")} className="button" onClick={()=>decide("APPROVE")}>Approve eligible gate</button><button disabled={!canDecide(workflow.state,"REJECT")} className="button danger" onClick={()=>decide("REJECT")}>Reject</button><button disabled={!canDecide(workflow.state,"RESEARCH_MORE")} className="button secondary" onClick={()=>decide("RESEARCH_MORE")}>Research more</button><button disabled={!canDecide(workflow.state,"GO_BACK")} className="button secondary" onClick={()=>decide("GO_BACK")}>Go back</button></div><p className="meta" style={{marginTop:20}}>AI cannot operate these approval controls. Every action is written to the project audit trail.</p></aside></div></main>
}
